language: python
sudo: false
python: 2.7
env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-djangomaster
  - TOX_ENV=flake8
matrix:
  allow_failures:
    - env: TOX_ENV=py27-djangomaster
    - env: TOX_ENV=flake8
install:
  - pip install tox
script:
    - tox -e $TOX_ENV -- --cov premis_event_service --cov-report html

before_install:
    - pip install codecov 

after_success:
    - codecov
