language: python
sudo: false
matrix:
     include:
        - python: 3.5
          env: TOX_ENV=py35
        - python: 3.6
          env: TOX_ENV=py36
        - python: 3.7
          env: TOX_ENV=py37
        - python: 3.7
          env: TOX_ENV=py37-flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
