language: python
matrix:
     include:
        - python: 3.6
          env: TOX_ENV=py36-django111
        - python: 3.7
          env: TOX_ENV=py37-django111
        - python: 3.7
          env: TOX_ENV=py37-flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
