version: '2'
services:
    db:
        image: mysql:5.5
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=premis_local

    app:
        extends:
            service: base
        depends_on:
            - db
        environment:
            - DJANGO_SETTINGS_MODULE=premis_event_service.settings
        command: python manage.py runserver 0.0.0.0:80
        ports:
            - "8000:80"
        links:
            - db

    base:        
        build: .
        volumes:
            - .:/app/

    test:
        extends:
            service: base
        entrypoint: py.test
        links:
            - db

    manage:
        extends:
            service: base
        entrypoint: /app/manage.py
        links:
            - db
