services:
    db:
        image: mariadb:10.4
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=premis_local

    web:
        build: .
        depends_on:
            - db
        environment:
            - DJANGO_SETTINGS_MODULE=tests.settings
            # Comment for sqlite
            - PES_BACKEND=mysql
            # Comment to disable debug toolbar.
            - PES_DEBUG_TOOLBAR=on
            # Uncomment for query logging.
            # - PES_DBDEBUG=on
        volumes:
            - .:/app/
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        links:
            - db
