# Generated by Django 2.2.28 on 2023-01-19 15:11

from django.db import migrations, models
import premis_event_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('premis_event_service', '0004_auto_20191008_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_identifier',
            field=models.CharField(db_index=True, default=premis_event_service.models.get_event_identifier_default, editable=False, help_text='Unique identifier for an event. example: urn:uuid:12345678-1234-5678-1234-567812345678', max_length=64, unique=True),
        ),
    ]
