# Generated by Django 4.1.7 on 2023-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premis_event_service', '0005_auto_20230119_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ordinal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
