name: Test django-premis-event-service

on: [push, pull_request, workflow_dispatch]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start the app
        run: docker compose up -d db web
      - name: Run the tests and ruff
        run: docker compose run --rm tox
